/* Generated By:JavaCC: Do not edit this line. llvmirConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface llvmirConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ascii_letter = 1;
  /** RegularExpression Id. */
  int letter = 2;
  /** RegularExpression Id. */
  int escape_letter = 3;
  /** RegularExpression Id. */
  int decimal_digit = 4;
  /** RegularExpression Id. */
  int hex_digit = 5;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int WHITESPACE = 7;
  /** RegularExpression Id. */
  int name = 8;
  /** RegularExpression Id. */
  int escape_name = 9;
  /** RegularExpression Id. */
  int quoted_name = 10;
  /** RegularExpression Id. */
  int id = 11;
  /** RegularExpression Id. */
  int global_ident = 12;
  /** RegularExpression Id. */
  int global_name = 13;
  /** RegularExpression Id. */
  int global_id = 14;
  /** RegularExpression Id. */
  int local_ident = 15;
  /** RegularExpression Id. */
  int local_name = 16;
  /** RegularExpression Id. */
  int local_id = 17;
  /** RegularExpression Id. */
  int label_ident = 18;
  /** RegularExpression Id. */
  int attr_group_id = 19;
  /** RegularExpression Id. */
  int comdat_name = 20;
  /** RegularExpression Id. */
  int metadata_name = 21;
  /** RegularExpression Id. */
  int metadata_id = 22;
  /** RegularExpression Id. */
  int int_lit = 23;
  /** RegularExpression Id. */
  int decimal_lit = 24;
  /** RegularExpression Id. */
  int decimals = 25;
  /** RegularExpression Id. */
  int float_lit = 26;
  /** RegularExpression Id. */
  int frac_lit = 27;
  /** RegularExpression Id. */
  int sign = 28;
  /** RegularExpression Id. */
  int sci_lit = 29;
  /** RegularExpression Id. */
  int HexFPConstant = 30;
  /** RegularExpression Id. */
  int HexFP80Constant = 31;
  /** RegularExpression Id. */
  int HexFP128Constant = 32;
  /** RegularExpression Id. */
  int HexPPC128Constant = 33;
  /** RegularExpression Id. */
  int HexHalfConstant = 34;
  /** RegularExpression Id. */
  int float_hex_lit = 35;
  /** RegularExpression Id. */
  int string_lit = 36;
  /** RegularExpression Id. */
  int quoted_string = 37;
  /** RegularExpression Id. */
  int int_type = 38;
  /** RegularExpression Id. */
  int eq = 39;
  /** RegularExpression Id. */
  int lbrace = 40;
  /** RegularExpression Id. */
  int rbrace = 41;
  /** RegularExpression Id. */
  int exclam = 42;
  /** RegularExpression Id. */
  int comma = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ascii_letter>",
    "<letter>",
    "<escape_letter>",
    "<decimal_digit>",
    "<hex_digit>",
    "<COMMENT>",
    "<WHITESPACE>",
    "<name>",
    "<escape_name>",
    "<quoted_name>",
    "<id>",
    "<global_ident>",
    "<global_name>",
    "<global_id>",
    "<local_ident>",
    "<local_name>",
    "<local_id>",
    "<label_ident>",
    "<attr_group_id>",
    "<comdat_name>",
    "<metadata_name>",
    "<metadata_id>",
    "<int_lit>",
    "<decimal_lit>",
    "<decimals>",
    "<float_lit>",
    "<frac_lit>",
    "<sign>",
    "<sci_lit>",
    "<HexFPConstant>",
    "<HexFP80Constant>",
    "<HexFP128Constant>",
    "<HexPPC128Constant>",
    "<HexHalfConstant>",
    "<float_hex_lit>",
    "<string_lit>",
    "<quoted_string>",
    "<int_type>",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"!\"",
    "\",\"",
  };

}
