/* Generated By:JavaCC: Do not edit this line. llvmirConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface llvmirConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ascii_letter = 1;
  /** RegularExpression Id. */
  int letter = 2;
  /** RegularExpression Id. */
  int escape_letter = 3;
  /** RegularExpression Id. */
  int decimal_digit = 4;
  /** RegularExpression Id. */
  int hex_digit = 5;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int WHITESPACE = 7;
  /** RegularExpression Id. */
  int name = 8;
  /** RegularExpression Id. */
  int escape_name = 9;
  /** RegularExpression Id. */
  int quoted_name = 10;
  /** RegularExpression Id. */
  int id = 11;
  /** RegularExpression Id. */
  int global_ident = 12;
  /** RegularExpression Id. */
  int global_name = 13;
  /** RegularExpression Id. */
  int global_id = 14;
  /** RegularExpression Id. */
  int local_ident = 15;
  /** RegularExpression Id. */
  int local_name = 16;
  /** RegularExpression Id. */
  int local_id = 17;
  /** RegularExpression Id. */
  int label_ident = 18;
  /** RegularExpression Id. */
  int attr_group_id = 19;
  /** RegularExpression Id. */
  int comdat_name = 20;
  /** RegularExpression Id. */
  int metadata_name = 21;
  /** RegularExpression Id. */
  int metadata_id = 22;
  /** RegularExpression Id. */
  int int_lit = 23;
  /** RegularExpression Id. */
  int decimal_lit = 24;
  /** RegularExpression Id. */
  int decimals = 25;
  /** RegularExpression Id. */
  int float_lit = 26;
  /** RegularExpression Id. */
  int frac_lit = 27;
  /** RegularExpression Id. */
  int sign = 28;
  /** RegularExpression Id. */
  int sci_lit = 29;
  /** RegularExpression Id. */
  int HexFPConstant = 30;
  /** RegularExpression Id. */
  int HexFP80Constant = 31;
  /** RegularExpression Id. */
  int HexFP128Constant = 32;
  /** RegularExpression Id. */
  int HexPPC128Constant = 33;
  /** RegularExpression Id. */
  int HexHalfConstant = 34;
  /** RegularExpression Id. */
  int float_hex_lit = 35;
  /** RegularExpression Id. */
  int string_lit = 36;
  /** RegularExpression Id. */
  int quoted_string = 37;
  /** RegularExpression Id. */
  int int_type = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ascii_letter>",
    "<letter>",
    "<escape_letter>",
    "<decimal_digit>",
    "<hex_digit>",
    "<COMMENT>",
    "<WHITESPACE>",
    "<name>",
    "<escape_name>",
    "<quoted_name>",
    "<id>",
    "<global_ident>",
    "<global_name>",
    "<global_id>",
    "<local_ident>",
    "<local_name>",
    "<local_id>",
    "<label_ident>",
    "<attr_group_id>",
    "<comdat_name>",
    "<metadata_name>",
    "<metadata_id>",
    "<int_lit>",
    "<decimal_lit>",
    "<decimals>",
    "<float_lit>",
    "<frac_lit>",
    "<sign>",
    "<sci_lit>",
    "<HexFPConstant>",
    "<HexFP80Constant>",
    "<HexFP128Constant>",
    "<HexPPC128Constant>",
    "<HexHalfConstant>",
    "<float_hex_lit>",
    "<string_lit>",
    "<quoted_string>",
    "<int_type>",
    "\"source_filename\"",
    "\"=\"",
    "\"target\"",
    "\"datalayout\"",
    "\"triple\"",
    "\"module\"",
    "\"asm\"",
    "\"type\"",
    "\"opaque\"",
    "\"comdat\"",
    "\"any\"",
    "\"exactmatch\"",
    "\"largest\"",
    "\"noduplicates\"",
    "\"samesize\"",
    "\",\"",
    "\"externally_initialized\"",
    "\"constant\"",
    "\"global\"",
    "\"declare\"",
    "\"define\"",
    "\"(\"",
    "\")\"",
    "\"...\"",
    "\"{\"",
    "\"}\"",
    "\"attributes\"",
    "\"!\"",
    "\"distinct\"",
    "\"void\"",
    "\"half\"",
    "\"float\"",
    "\"double\"",
    "\"fp128\"",
    "\"x86_fp80\"",
    "\"ppc_fp128\"",
    "\"*\"",
    "\"addrspace\"",
    "\"<\"",
    "\"x\"",
    "\">\"",
    "\"label\"",
    "\"metadata\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"c\"",
    "\"zeroinitializer\"",
    "\"undef\"",
    "\"add\"",
    "\"fadd\"",
    "\"sub\"",
    "\"fsub\"",
    "\"mul\"",
    "\"fmul\"",
    "\"udiv\"",
    "\"sdiv\"",
    "\"fdiv\"",
    "\"urem\"",
    "\"srem\"",
    "\"frem\"",
    "\"shl\"",
    "\"lshr\"",
    "\"ashr\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"extractelement\"",
    "\"insertelement\"",
    "\"shufflevector\"",
    "\"extractvalue\"",
    "\"insertvalue\"",
    "\"getelementptr\"",
    "\"trunc\"",
    "\"to\"",
    "\"zext\"",
    "\"sext\"",
    "\"fptrunc\"",
    "\"fpext\"",
    "\"fptoui\"",
    "\"fptosi\"",
    "\"uitofp\"",
    "\"sitofp\"",
    "\"ptrtoint\"",
    "\"inttoptr\"",
    "\"bitcast\"",
    "\"addrspacecast\"",
    "\"icmp\"",
    "\"fcmp\"",
    "\"select\"",
    "\"nuw\"",
    "\"nsw\"",
    "\"arcp\"",
    "\"fast\"",
    "\"ninf\"",
    "\"nnan\"",
    "\"nsz\"",
    "\"exact\"",
    "\"alloca\"",
    "\"load\"",
    "\"volatile\"",
    "\"store\"",
    "\"fence\"",
    "\"singlethread\"",
    "\"acq_rel\"",
    "\"acquire\"",
    "\"monotonic\"",
    "\"release\"",
    "\"seq_cst\"",
    "\"unordered\"",
    "\"cmpxchg\"",
    "\"weak\"",
    "\"atomicrmw\"",
    "\"max\"",
    "\"min\"",
    "\"nand\"",
    "\"umax\"",
    "\"umin\"",
    "\"xchg\"",
    "\"eq\"",
    "\"ne\"",
    "\"ugt\"",
    "\"uge\"",
    "\"ult\"",
    "\"ule\"",
    "\"sgt\"",
    "\"sge\"",
    "\"slt\"",
    "\"sle\"",
    "\"oeq\"",
    "\"ogt\"",
    "\"oge\"",
    "\"olt\"",
    "\"ole\"",
    "\"one\"",
    "\"ord\"",
    "\"ueq\"",
    "\"une\"",
    "\"uno\"",
    "\"phi\"",
    "\"call\"",
    "\"tail\"",
    "\"musttail\"",
    "\"notail\"",
    "\"va_arg\"",
    "\"landingpad\"",
    "\"cleanup\"",
    "\"catch\"",
    "\"filter\"",
    "\"catchpad\"",
    "\"within\"",
    "\"cleanuppad\"",
    "\"none\"",
    "\"ret\"",
    "\"br\"",
    "\"switch\"",
    "\"indirectbr\"",
    "\"invoke\"",
    "\"unwind\"",
    "\"resume\"",
    "\"catchswitch\"",
    "\"caller\"",
    "\"catchret\"",
    "\"from\"",
    "\"cleanupret\"",
    "\"unreachable\"",
    "\"appending\"",
    "\"available_externally\"",
    "\"common\"",
    "\"internal\"",
    "\"linkonce\"",
    "\"linkonce_odr\"",
    "\"private\"",
    "\"weak_odr\"",
    "\"extern_weak\"",
    "\"external\"",
    "\"default\"",
    "\"hidden\"",
    "\"protected\"",
    "\"dllimport\"",
    "\"dllexport\"",
    "\"thread_local\"",
    "\"localdynamic\"",
    "\"initialexec\"",
    "\"localexec\"",
    "\"local_unnamed_addr\"",
    "\"unnamed_addr\"",
    "\"section\"",
    "\"align\"",
    "\"gc\"",
    "\"prefix\"",
    "\"prologue\"",
    "\"personality\"",
    "\"byval\"",
    "\"dereferenceable\"",
    "\"dereferenceable_or_null\"",
    "\"inalloca\"",
    "\"inreg\"",
    "\"nest\"",
    "\"noalias\"",
    "\"nocapture\"",
    "\"nonnull\"",
    "\"readnone\"",
    "\"readonly\"",
    "\"returned\"",
    "\"signext\"",
    "\"sret\"",
    "\"swifterror\"",
    "\"swiftself\"",
    "\"writeonly\"",
    "\"zeroext\"",
    "\"alignstack\"",
    "\"allocsize\"",
    "\"alwaysinline\"",
    "\"argmemonly\"",
    "\"builtin\"",
    "\"cold\"",
    "\"convergent\"",
    "\"inaccessiblemem_or_argmemonly\"",
    "\"inaccessiblememonly\"",
    "\"inlinehint\"",
    "\"jumptable\"",
    "\"minsize\"",
    "\"naked\"",
    "\"nobuiltin\"",
    "\"noduplicate\"",
    "\"noimplicitfloat\"",
    "\"noinline\"",
    "\"nonlazybind\"",
    "\"norecurse\"",
    "\"noredzone\"",
    "\"noreturn\"",
    "\"nounwind\"",
    "\"optnone\"",
    "\"optsize\"",
    "\"returns_twice\"",
    "\"safestack\"",
    "\"sanitize_address\"",
    "\"sanitize_memory\"",
    "\"sanitize_thread\"",
    "\"ssp\"",
    "\"sspreq\"",
    "\"sspstrong\"",
    "\"uwtable\"",
    "\"amdgpu_cs\"",
    "\"amdgpu_gs\"",
    "\"amdgpu_kernel\"",
    "\"amdgpu_ps\"",
    "\"amdgpu_vs\"",
    "\"anyregcc\"",
    "\"arm_aapcs_vfpcc\"",
    "\"arm_aapcscc\"",
    "\"arm_apcscc\"",
    "\"avr_intrcc\"",
    "\"avr_signalcc\"",
    "\"cc\"",
    "\"ccc\"",
    "\"coldcc\"",
    "\"cxx_fast_tlscc\"",
    "\"fastcc\"",
    "\"ghccc\"",
    "\"hhvm_ccc\"",
    "\"hhvmcc\"",
    "\"intel_ocl_bicc\"",
    "\"msp430_intrcc\"",
    "\"preserve_allcc\"",
    "\"preserve_mostcc\"",
    "\"ptx_device\"",
    "\"ptx_kernel\"",
    "\"spir_func\"",
    "\"spir_kernel\"",
    "\"swiftcc\"",
    "\"webkit_jscc\"",
    "\"x86_64_sysvcc\"",
    "\"x86_64_win64cc\"",
    "\"x86_fastcallcc\"",
    "\"x86_intrcc\"",
    "\"x86_regcallcc\"",
    "\"x86_stdcallcc\"",
    "\"x86_thiscallcc\"",
    "\"x86_vectorcallcc\"",
    "\"inbounds\"",
  };

}
